config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  resources :users

  resources :movies, except: [:destroy, :edit]

  resources :pops, only: [:create, :patch]

  resources :reviews, except: :index

  resources :comments, except: :index

  resources :movies do
    resources :comments
  end

  resources :reviews do
    resources :comments
  end

  post '/reviews/:review_id/pops/:type', to: 'pops#create', as: 'kernz'
  patch '/reviews/:review_id/pops/:id/:type', to: 'pops#update', as: 'update_kern'

  resources :classifications, only: [:show, :index]

  get '/login', to: 'users#login', as: 'login_page'
  post '/login', to: 'users#new_session', as: 'login'
  delete '/logout', to: 'users#logout', as: 'logout'

  get '/results', to: 'results#index'

  get '/401', to: 'errors#unauthorized'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.order('created_at DESC').limit(6)
  end

  def new
    @movie = Movie.new
  end

  def create
    movie = OMDB.id(params[:imdb_id])

    @movie = Movie.new
    @movie.title = movie.title
    @movie.plot = movie.plot
    @movie.year = movie.year
    @movie.poster = movie.poster
    @movie.imdb_id = params[:imdb_id]

    if @movie.save
      add_genres(movie.genre, @movie.id) if movie.genre
      redirect_to movie_path(@movie)
    else
      render template: 'movies/new'
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @comment = Comment.last
    # @user= User.find(@comment.user_id)
    render template: 'movies/show'
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :summary, :year, :poster)
  end

  def add_genres(genres_string, movie_id)
    genres_string.split(', ').each do |genre|
      genre_obj = Genre.find_by(title: genre)
      unless genre_obj == nil
        Classification.create(genre_id: genre_obj.id, movie_id: movie_id)
      end
    end
  end
end

app/views/movies/_movie_card.html.erb
<div class="col s4 m4">
  <div class="card medium">
    <div class="card-image">
      <img src="<%= movie.poster %>">

    </div>
    <div class="card-content">
      <span class="card-title">
        <%= link_to movie.title, movie_path(movie), class: 'movie_title' %>
      </span>
      <p><%= movie.year %></p>
    </div>
  </div>
</div>

app/views/movies/_review_partial.html.erb
<div class='vote block center'>
  <% if user_voted?(current_user) %>
    <%= link_to image_tag("pop 2.png", size: "35x35"), update_kern_path(review_id: review.id, id: get_pop(review), type: 'upvote'), html: {name: 'upvote', class: 'upvote'}, method: :patch %><br>
    <span class='count'><%= review.pops.sum(:popped) %></span><br>
    <%= link_to image_tag("kernz 2.png", size: "20x20"), update_kern_path(review_id: review.id, id: get_pop(review), type: 'downvote'), html: {name: 'downvote', class: 'downvote'}, method: :patch %><br>
  <% else %>
    <%= link_to image_tag("pop 2.png", size: "35x35"), kernz_path(review_id: review.id, type: 'upvote'), html: {name: 'upvote', class: 'upvote new_pop vote'}, method: :post %><br>
    <span class='count'><%= review.pops.sum(:popped) %></span><br>
    <%= link_to image_tag("kernz 2.png", size: "20x20"), kernz_path(review_id: review.id, type: 'downvote'), html: {name: 'downvote', class: 'downvote new_pop vote'}, method: :post %><br>
  <% end %>
</div>

<div class='review block'>
  <%user=User.find(review.user_id)%>
  <h5 class='noMargin'><%=user.username%> rated this film a: <%=review.rating%> </h5>
  <%= "TRUSTED USER" if user.trusted%>
  <div class='comment-pad'><%=review.body%></div>
  <div class='buttons-pad'><%=link_to "#{review.comments.length} comments", review_comments_path(review) %>

  <% if review.user_id == current_user.id %>
    <%=link_to "delete review", review_path(review), method: :delete, class: 'btn' %></div>
  <% end %>
</div>

app/views/movies/index.html.erb
<h4>Recently added films</h4>

<div class="row">
<% @movies.each do |movie| %>
  <%= render partial: 'movie_card', locals: {movie: movie} %>
<% end %>
</div>

app/views/movies/new.html.erb
<h2>Find a Film</h2>

<div class="row">
  <div class="col s12 m4 l2 hidden-text">LUMOS</div>
  <div class="col s12 m4 l8">
    <%= form_for @movie, url: results_path, method: :get do |f| %>
      <div class="input-field">
        <%= f.text_field :title %>
        <%= f.label :title %>
      </div>

      <div class="input-field">
        <%= f.submit 'search', class: 'btn' %>
      </div>
    <% end %>
  </div>
  <div class="col s12 m4 l2 hidden-text">LUMOS</div>
</div>

app/views/movies/show.html.erb
<div class='row left-align'>
  <div class='col s6'><img class='movie-summary' src="<%=@movie.poster%>"></div>
  <div><h5><%=@movie.title%></h5></div>
	<hr>
  <div>
		<strong>Plot</strong>
		<p><%=@movie.plot%></p>
	</div>
	<hr>
  <div><%=link_to " View comments (#{@movie.comments.length})", movie_comments_path(@movie) %></div>
</div>

<div class='left-align'>
	<% if current_user %>
    <% if !user_reviewed?(@movie.id) %>
  	  <%= form_for :review, url: reviews_path, html: {id: :new_review_form}, remote: true do |f| %>
  	    <div class='row review_form_body'>
  	      <%= f.label :body, 'Write a review', class: 's1' %><br>
  	      <%= f.text_area :body, placeholder: "This movie is poppin!", class: ' s12' %>
  	    </div>
  	    <div class='row'>
  	      <%= f.label :rating, 'Rating:', class: 'col s1' %>
  	      <span id="rating_value">3</span>
          <%= f.range_field :rating, min: 1, max: 5, class: 'col s3', id: "slider" %>
  	    </div>

  	    <input type="hidden" name="movie_id" value="<%= @movie.id %>">
  	    <%= f.submit 'submit', class: 'btn' %>
  	  <% end %>
      <hr>
    <% end %>
	<% end %>

  <ul class='reviews_section'>
  <%if @movie.reviews.length > 0%>
    <% @movie.reviews.each do |review| %>
       <li class='growWithChild addLeftBorder'><%=render partial: 'review_partial', locals:{review: review, movie: @movie} %></li>
    <%end%>
  <%end%>
  </ul>
</div>