config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  resources :users

  resources :movies, except: [:destroy, :edit]

  resources :pops, only: [:create, :patch]

  resources :reviews, except: :index

  resources :comments, except: :index

  resources :movies do
    resources :comments
  end

  resources :reviews do
    resources :comments
  end

  post '/reviews/:review_id/pops/:type', to: 'pops#create', as: 'kernz'
  patch '/reviews/:review_id/pops/:id/:type', to: 'pops#update', as: 'update_kern'

  resources :classifications, only: [:show, :index]

  get '/login', to: 'users#login', as: 'login_page'
  post '/login', to: 'users#new_session', as: 'login'
  delete '/logout', to: 'users#logout', as: 'logout'

  get '/results', to: 'results#index'

  get '/401', to: 'errors#unauthorized'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movie Zoo</title>

	<%= javascript_include_tag 'application' %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all' %>


  <%= csrf_meta_tags %>
</head>
<body>
  <header>
	<nav class="top-nav teal">
    <a href="#" id='sidebar-menu-icon' data-activates="nav-mobile" class="button-collapse top-nav full hide-on-large-only"><i class="mdi-navigation-menu"></i></a>
    <div class="container">

      <div class="nav-wrapper teal">
  			<h4><%= link_to 'Movie Zoo', root_path, class: 'page-title' %></h4>
        <ul class="right">
            <li><%= link_to 'browse movies', new_movie_path %></li>
          <% if current_user -%>
  		      <li><%= link_to 'logout', logout_path, method: :delete %></li>
  		    <% else %>
  		      <li><%= link_to 'login', login_page_path %></li>
  		      <li><%= link_to 'create account', new_user_path %></li>
  		    <% end %>
          <li class="search">
        </li>
        </ul>

      </div>
    </div>
  </nav>

    <ul id="nav-mobile" class="side-nav fixed">
      <li><%= link_to 'View All Movies', classifications_path %></li>
      <li>Genres</li>
      <% get_genres.each do |genre| -%>
        <li class="genre"><%= link_to genre.title, classification_path(genre.id) %></li>
      <% end %>
    </ul>
</header>



<main>
  <div class="container">
  <%= yield %>
  </div>
</main>
</body>
</html>